import Head from 'next/head'
// import Image from 'next/image'
import styles from '../styles/Home.module.css'
import React, { useEffect, useState } from 'react'
import Link from 'next/link'

export default function Home(props) {
  const [blogs,setBlogs]=useState(props.allBlogs);

// use in the case of not using server side reandering.

// useEffect(()=>{
//     fetch('http://localhost:3001/api/blogs').then((a)=>{
//         return a.json();})
//      .then((parsed)=>{
//         setBlogs(parsed)
//      })   
    
// },[])

  return (
    <>

    <div className={styles.container}>
      <Head>
        <title>Hunting Coder</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="keywords" content="nextjs, huntingcoder blog, hunting coder" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <Script src='/sc.js' strategy="lazyOnload"></Script> */}

      <main className={styles.main}>
        <div className={styles.imagewrap}>
          {/* <Image className={styles.myImg} src="/homeimg.jfif" width={237} height={158}/> */}
          <img className={styles.myImg} src="/home.jpg" width={237} height={158} />
        </div>
        <h1 className={styles.title}>
          <span className='dummy'>&lt;HuntingCoder/&gt;</span>
        </h1>


        {/* <div className={`${styles1.con} ${styles2.con}`}> */}
  

        <div className="blogs">
          <h2>Latest Blogs</h2>
          {blogs.map((blogItem)=>{
        return( <div  className={styles.blogItem}>
         <Link href={`blogpost/${blogItem.slug}`}>
         <h3> {blogItem.topic} </h3></Link>
         <p> {blogItem.content.substr(0,100)}... </p>
         <button className={styles.btn}><Link href={`blogpost/${blogItem.slug}`}>Read More</Link></button>
       </div>
    )})}
        </div>
      </main>

      <footer className={styles.footer}>
      </footer>
    </div></>
  )
}

// server side randering method
// This gets called on every request
export async function getServerSideProps(context) {
  // Fetch data from external API
  const data = await fetch('http://localhost:3000/api/blogs')
  const allBlogs = await data.json()
 
  // Pass data to the page via props
  return { props: { allBlogs } }
}
